# Generated by Django 3.2.2 on 2021-05-07 17:54

from django.db import migrations, models


def add_world_cup_2018(apps, schema_editor):
    Competition = apps.get_model("betting", "Competition")
    Competition.objects.create(name="FIFA World Cup 2018")


class Migration(migrations.Migration):

    dependencies = [
        ("betting", "0002_auto_20180508_2114"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RunPython(add_world_cup_2018),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
