# Generated by Django 3.2.2 on 2021-05-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0007_group_competition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='slug',
        ),
    ]
