# Generated by Django 3.2.2 on 2021-05-21 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("betting", "0009_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCompetition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField(default=0)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="betting.competition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="competition",
            name="users",
            field=models.ManyToManyField(
                through="betting.UserCompetition", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
