# Generated by Django 2.0.4 on 2018-04-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
