# Generated by Django 3.2.2 on 2021-05-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0004_game_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='slug',
            field=models.SlugField(default='world-cup-2018'),
            preserve_default=False,
        ),
    ]
