# Generated by Django 3.2.2 on 2021-05-08 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0006_auto_20210508_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='betting.competition'),
        ),
    ]
