# Generated by Django 3.2.2 on 2021-05-22 00:44

from django.db import migrations


def do(apps, schema_editor):
    Competition = apps.get_model("betting", "Competition")
    UserCompetition = apps.get_model("betting", "UserCompetition")
    User = apps.get_model("betting", "User")

    worldcup = Competition.objects.get(slug="world-cup-2018")
    for user in User.objects.all():
        UserCompetition.objects.create(
            user=user, competition=worldcup, points=user.points
        )


class Migration(migrations.Migration):

    dependencies = [
        ("betting", "0010_auto_20210521_0153"),
    ]

    operations = [
        migrations.RunPython(do),
    ]
