# Generated by Django 3.1b1 on 2020-07-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("template_name", models.SlugField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        max_length=60,
                    ),
                ),
                ("subject", models.CharField(max_length=500)),
                ("preheader", models.CharField(blank=True, max_length=500, null=True)),
                ("from_email", models.CharField(blank=True, max_length=500, null=True)),
                ("content", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
