# Generated by Django 3.1b1 on 2020-07-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="cta_content",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="email",
            name="cta_href",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="email",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=60,
            ),
        ),
    ]
