# Generated by Django 3.1b1 on 2020-07-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0003_email_signature"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("to", models.EmailField(max_length=254)),
                ("template_name", models.SlugField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
