# Generated by Django 3.1b1 on 2020-07-25 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0004_activity"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Activity",
            new_name="EmailActivity",
        ),
    ]
