# Generated by Django 3.1b1 on 2020-08-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0005_auto_20200725_1824"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailactivity",
            name="once",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
