# Generated by Django 3.1 on 2020-09-09 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0006_emailactivity_once"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailactivity",
            options={"verbose_name_plural": "Email Activities"},
        ),
    ]
