# Generated by Django 3.1 on 2021-03-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0008_email_subscription_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="subscription_group",
            field=models.CharField(
                blank=True,
                default="14002",
                help_text="sendgrid subscription group id",
                max_length=500,
                null=True,
            ),
        ),
    ]
