# Generated by Django 3.1 on 2021-03-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0009_auto_20210302_1812"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="subscription_group",
            field=models.CharField(
                blank=True,
                help_text="sendgrid subscription group id",
                max_length=500,
                null=True,
            ),
        ),
    ]
